"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("incomes", [
      {
        id: 1,
        user_id: 1,
        fixed_income: 76355,
        varied_income: 0,
        category_inc_id: 4,
        description:
          "Personal history of (corrected) congenital malform of eye",
        createdAt: "2022-03-21",
        updatedAt: "2022-03-07",
      },
      {
        id: 2,
        user_id: 2,
        fixed_income: 198554,
        varied_income: 0,
        category_inc_id: 1,
        description:
          "Passenger in hv veh injured in clsn w pedl cyc nontraf, subs",
        createdAt: "2022-04-17",
        updatedAt: "2022-03-24",
      },
      {
        id: 3,
        user_id: 3,
        fixed_income: 39747,
        varied_income: 0,
        category_inc_id: 4,
        description: "Unspecified abnormal finding in cerebrospinal fluid",
        createdAt: "2022-03-20",
        updatedAt: "2022-04-21",
      },
      {
        id: 4,
        user_id: 4,
        fixed_income: 148270,
        varied_income: 0,
        category_inc_id: 1,
        description: "Nontraumatic subarachnoid hemorrhage",
        createdAt: "2022-04-05",
        updatedAt: "2022-02-18",
      },
      {
        id: 5,
        user_id: 5,
        fixed_income: 198537,
        varied_income: 0,
        category_inc_id: 3,
        description: "Nondisp oblique fx shaft of unsp fibula, 7thR",
        createdAt: "2022-02-13",
        updatedAt: "2022-04-14",
      },
      {
        id: 6,
        user_id: 6,
        fixed_income: 190169,
        varied_income: 0,
        category_inc_id: 1,
        description: "Toxic effect of organic solvents, accidental, subs",
        createdAt: "2022-03-25",
        updatedAt: "2022-03-29",
      },
      {
        id: 7,
        user_id: 7,
        fixed_income: 184923,
        varied_income: 0,
        category_inc_id: 1,
        description:
          "Corros first deg mult fingers (nail), not including thumb",
        createdAt: "2022-02-12",
        updatedAt: "2022-04-02",
      },
      {
        id: 8,
        user_id: 8,
        fixed_income: 192153,
        varied_income: 0,
        category_inc_id: 2,
        description: "Poisoning by oth antacids and anti-gstrc-sec drugs, acc",
        createdAt: "2022-03-26",
        updatedAt: "2022-04-01",
      },
      {
        id: 9,
        user_id: 9,
        fixed_income: 177595,
        varied_income: 0,
        category_inc_id: 4,
        description: "Punctate keratitis, left eye",
        createdAt: "2022-02-12",
        updatedAt: "2022-04-06",
      },
      {
        id: 10,
        user_id: 10,
        fixed_income: 136245,
        varied_income: 0,
        category_inc_id: 4,
        description:
          "Nondisp fx of olecran pro w/o intartic extn unsp ulna, 7thB",
        createdAt: "2022-02-25",
        updatedAt: "2022-02-21",
      },
      {
        id: 11,
        user_id: 11,
        fixed_income: 186726,
        varied_income: 0,
        category_inc_id: 1,
        description: "Contusion of unspecified back wall of thorax, sequela",
        createdAt: "2022-04-11",
        updatedAt: "2022-02-10",
      },
      {
        id: 12,
        user_id: 12,
        fixed_income: 112243,
        varied_income: 0,
        category_inc_id: 3,
        description: "Enteropathic arthropathies, right shoulder",
        createdAt: "2022-03-03",
        updatedAt: "2022-03-06",
      },
      {
        id: 13,
        user_id: 13,
        fixed_income: 56607,
        varied_income: 0,
        category_inc_id: 4,
        description: "Laceration w fb of l idx fngr w damage to nail, init",
        createdAt: "2022-03-02",
        updatedAt: "2022-02-25",
      },
      {
        id: 14,
        user_id: 14,
        fixed_income: 30203,
        varied_income: 0,
        category_inc_id: 4,
        description: "Benign neuroendocrine tumors",
        createdAt: "2022-03-08",
        updatedAt: "2022-02-16",
      },
      {
        id: 15,
        user_id: 15,
        fixed_income: 124399,
        varied_income: 0,
        category_inc_id: 4,
        description:
          "Corros w resulting rupture and dest of unsp eyeball, sequela",
        createdAt: "2022-02-23",
        updatedAt: "2022-02-18",
      },
      {
        id: 16,
        user_id: 16,
        fixed_income: 70884,
        varied_income: 0,
        category_inc_id: 2,
        description: "Disp fx of less trochanter of unsp femr, 7thH",
        createdAt: "2022-04-14",
        updatedAt: "2022-03-09",
      },
      {
        id: 17,
        user_id: 17,
        fixed_income: 41320,
        varied_income: 0,
        category_inc_id: 4,
        description: "Burn due to fishing boat on fire",
        createdAt: "2022-02-25",
        updatedAt: "2022-04-19",
      },
      {
        id: 18,
        user_id: 18,
        fixed_income: 151437,
        varied_income: 0,
        category_inc_id: 1,
        description:
          "Toxic effect of benzene, accidental (unintentional), sequela",
        createdAt: "2022-03-26",
        updatedAt: "2022-02-26",
      },
      {
        id: 19,
        user_id: 19,
        fixed_income: 80922,
        varied_income: 0,
        category_inc_id: 4,
        description: "Explosion and rupture of other gas cylinder",
        createdAt: "2022-04-15",
        updatedAt: "2022-02-19",
      },
      {
        id: 20,
        user_id: 20,
        fixed_income: 142928,
        varied_income: 0,
        category_inc_id: 1,
        description:
          "Medial subluxation of unspecified ulnohumeral joint, sequela",
        createdAt: "2022-03-22",
        updatedAt: "2022-04-09",
      },
      {
        id: 21,
        user_id: 21,
        fixed_income: 36014,
        varied_income: 0,
        category_inc_id: 4,
        description: "Effusion, right elbow",
        createdAt: "2022-03-22",
        updatedAt: "2022-04-20",
      },
      {
        id: 22,
        user_id: 22,
        fixed_income: 58432,
        varied_income: 0,
        category_inc_id: 4,
        description:
          "Oth traum nondisp spondylolysis of second cervcal vert, sqla",
        createdAt: "2022-03-24",
        updatedAt: "2022-03-07",
      },
      {
        id: 23,
        user_id: 23,
        fixed_income: 122766,
        varied_income: 0,
        category_inc_id: 2,
        description: "Unsp trochan fx l femr, 7thF",
        createdAt: "2022-02-21",
        updatedAt: "2022-04-11",
      },
      {
        id: 24,
        user_id: 24,
        fixed_income: 69530,
        varied_income: 0,
        category_inc_id: 3,
        description: "Generalized contraction of visual field",
        createdAt: "2022-02-05",
        updatedAt: "2022-03-06",
      },
      {
        id: 25,
        user_id: 25,
        fixed_income: 98618,
        varied_income: 0,
        category_inc_id: 1,
        description:
          "Unsp injury of great saphenous at hip and thi lev, right leg",
        createdAt: "2022-03-07",
        updatedAt: "2022-03-12",
      },
      {
        id: 26,
        user_id: 26,
        fixed_income: 146277,
        varied_income: 0,
        category_inc_id: 4,
        description: "Displ seg fx shaft of humerus, left arm, init for opn fx",
        createdAt: "2022-03-16",
        updatedAt: "2022-03-06",
      },
      {
        id: 27,
        user_id: 27,
        fixed_income: 147964,
        varied_income: 0,
        category_inc_id: 3,
        description: "External constriction of eyelid and periocular area",
        createdAt: "2022-04-13",
        updatedAt: "2022-03-20",
      },
      {
        id: 28,
        user_id: 28,
        fixed_income: 63986,
        varied_income: 0,
        category_inc_id: 4,
        description: "Supraglottitis, unspecified",
        createdAt: "2022-03-29",
        updatedAt: "2022-03-26",
      },
      {
        id: 29,
        user_id: 29,
        fixed_income: 64526,
        varied_income: 0,
        category_inc_id: 1,
        description: "Unsp injury at C6 level of cervical spinal cord, sequela",
        createdAt: "2022-03-21",
        updatedAt: "2022-04-02",
      },
      {
        id: 30,
        user_id: 30,
        fixed_income: 72338,
        varied_income: 0,
        category_inc_id: 2,
        description:
          "Wedge comprsn fx unsp lum vertebra, subs for fx w delay heal",
        createdAt: "2022-02-20",
        updatedAt: "2022-03-20",
      },
      {
        id: 31,
        user_id: 31,
        fixed_income: 166377,
        varied_income: 0,
        category_inc_id: 4,
        description: "Juvenile osteochondrosis of patella, left knee",
        createdAt: "2022-03-21",
        updatedAt: "2022-04-20",
      },
      {
        id: 32,
        user_id: 32,
        fixed_income: 159294,
        varied_income: 0,
        category_inc_id: 1,
        description:
          "Complete lesion at T1 level of thoracic spinal cord, init",
        createdAt: "2022-04-10",
        updatedAt: "2022-04-13",
      },
      {
        id: 33,
        user_id: 33,
        fixed_income: 111327,
        varied_income: 0,
        category_inc_id: 4,
        description: "Acute bronchiolitis due to respiratory syncytial virus",
        createdAt: "2022-03-19",
        updatedAt: "2022-02-15",
      },
      {
        id: 34,
        user_id: 34,
        fixed_income: 134971,
        varied_income: 0,
        category_inc_id: 1,
        description:
          "Unsp soft tissue disord related to use/pressure, unsp ank/ft",
        createdAt: "2022-04-15",
        updatedAt: "2022-04-12",
      },
      {
        id: 35,
        user_id: 35,
        fixed_income: 92554,
        varied_income: 0,
        category_inc_id: 4,
        description: "Poisoning by MAO inhib antidepressants, accidental, subs",
        createdAt: "2022-03-17",
        updatedAt: "2022-03-21",
      },
      {
        id: 36,
        user_id: 36,
        fixed_income: 185446,
        varied_income: 0,
        category_inc_id: 2,
        description: "Disp fx of med condyle of l femr, 7thC",
        createdAt: "2022-03-29",
        updatedAt: "2022-03-05",
      },
      {
        id: 37,
        user_id: 37,
        fixed_income: 191483,
        varied_income: 0,
        category_inc_id: 4,
        description: "Contusion of right forearm, sequela",
        createdAt: "2022-03-11",
        updatedAt: "2022-04-14",
      },
      {
        id: 38,
        user_id: 38,
        fixed_income: 193209,
        varied_income: 0,
        category_inc_id: 2,
        description:
          "Corrosion of third degree of unspecified palm, init encntr",
        createdAt: "2022-02-11",
        updatedAt: "2022-02-12",
      },
      {
        id: 39,
        user_id: 39,
        fixed_income: 119036,
        varied_income: 0,
        category_inc_id: 4,
        description: "Optic nerve hypoplasia, right eye",
        createdAt: "2022-03-20",
        updatedAt: "2022-04-04",
      },
      {
        id: 40,
        user_id: 40,
        fixed_income: 159278,
        varied_income: 0,
        category_inc_id: 4,
        description:
          "Displ longitud fx unsp patella, subs for clos fx w malunion",
        createdAt: "2022-04-05",
        updatedAt: "2022-04-21",
      },
      {
        id: 41,
        user_id: 41,
        fixed_income: 72917,
        varied_income: 0,
        category_inc_id: 1,
        description:
          "Lacerat flexor musc/fasc/tend l little finger at forarm lv",
        createdAt: "2022-02-21",
        updatedAt: "2022-03-23",
      },
      {
        id: 42,
        user_id: 42,
        fixed_income: 141677,
        varied_income: 0,
        category_inc_id: 4,
        description: "Other dislocation of right patella, subsequent encounter",
        createdAt: "2022-03-26",
        updatedAt: "2022-03-01",
      },
      {
        id: 43,
        user_id: 43,
        fixed_income: 131552,
        varied_income: 0,
        category_inc_id: 2,
        description: "Superficial frostbite of right arm, initial encounter",
        createdAt: "2022-03-06",
        updatedAt: "2022-02-26",
      },
      {
        id: 44,
        user_id: 44,
        fixed_income: 116817,
        varied_income: 0,
        category_inc_id: 2,
        description: "Poisoning by cannabis (derivatives), self-harm, subs",
        createdAt: "2022-03-18",
        updatedAt: "2022-03-06",
      },
      {
        id: 45,
        user_id: 45,
        fixed_income: 154289,
        varied_income: 0,
        category_inc_id: 3,
        description: "Poisoning by oth fibrin-affct drugs, self-harm, subs",
        createdAt: "2022-03-24",
        updatedAt: "2022-04-05",
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("incomes", null, {});
  },
};
