###
POST http://localhost:3001/users/register 
content-type: application/json

{
    "firstName" : "marcos",
    "lastName" : "weis",
    "email" : "marcos@dh.com"
}

###
GET  http://localhost:3001/users/list
content-type: application/json

###
POST http://localhost:3001/users/login
content-type: application/json

{   
    "email" : "marcos@dh.com",
    "password": "Marcos97w"
}
###
//le tenemos que indicar cual es el esquema de autorizacion que utilizamos
GET http://localhost:3001/budget
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmlja05hbWUiOiJNYXJjb3MiLCJpYXQiOjE2NDk3MDk3NDIsImV4cCI6MTY1MDMxNDU0Mn0.5TO3Tql-dTc2xcfvouOxJcUTfwqbdcAlTudkMG252P0
###
POST http://localhost:3001/users/checkingToken
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmlja05hbWUiOiJtYXJjb3MiLCJpYXQiOjE2NDk3MTMyMDksImV4cCI6MTY1MDMxODAwOX0.I4sX7p1Fep9U-YP8VxD7SpObOeadX6ummgZujIVKksI

###
GET http://localhost:3001/budget/categories_income
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmlja05hbWUiOiJtYXJjb3MiLCJpYXQiOjE2NDk3MTMyMDksImV4cCI6MTY1MDMxODAwOX0.I4sX7p1Fep9U-YP8VxD7SpObOeadX6ummgZujIVKksI

### 
GET http://localhost:3001/budget/income
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTEsIm5pY2tOYW1lIjoiTWFyY29zIiwiaWF0IjoxNjQ5ODgyMzY0LCJleHAiOjE2NTA0ODcxNjR9.a-w1SXWDOvqL9oVfHV1Klf6MNuUYa1XB5l0hkdJP3xs